#!/bin/bash

GIT_DIR=$HOME/.dotfiles2

git clone --bare git@github.com:rtogo/.dotfiles.git $GIT_DIR
function config {
   git --git-dir=$GIT_DIR --work-tree=$HOME $@
}
mkdir -p .dotfiles-backup
config checkout
if [ $? = 0 ]; then
	echo "Checked out config.";
else
	echo "Backing up pre-existing dotfiles...";
	config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
fi;
config checkout
config config status.showUntrackedFiles no
