#!/bin/bash

GIT_DIR=$HOME/.dotfiles
BACKUP_DIR=$HOME/.dotfiles-backup

function config {
   git --git-dir=$GIT_DIR --work-tree=$HOME $@
}

git clone --bare git@github.com:rtogo/.dotfiles.git $GIT_DIR >/dev/null 2>&1
config checkout >/dev/null 2>&1
if [ $? = 0 ]; then
	echo "Checked out dotfiles";
else
	echo "Backing up pre-existing dotfiles...";
	mkdir -p $BACKUP_DIR
	pre_existing_files=($(config checkout 2>&1 | egrep "^\s+" | awk {'print $1'}))
	for fullpath in "${pre_existing_files[@]}"
	do
		dirname=$(dirname $fullpath)
		if [[ $dirname != "." ]]; then
			mkdir -p "$BACKUP_DIR/$dirname"
		fi;
		mv "$fullpath" "$BACKUP_DIR/$fullpath"
		echo "$fullpath backed up into --> $BACKUP_DIR/$fullpath"
	done
	config checkout
	echo "Checked out dotfiles";
fi;
config config status.showUntrackedFiles no

