#!/bin/bash

GIT_DIR=$HOME/.dotfiles2

git clone --bare git@github.com:rtogo/.dotfiles.git $GIT_DIR
function config {
   git --git-dir=$GIT_DIR --work-tree=$HOME $@
}
config checkout
if [ $? = 0 ]; then
	echo "Checked out config.";
else
	echo "Backing up pre-existing dotfiles...";
	mkdir -p .dotfiles-backup
	config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dotfiles-backup/{}
	config checkout
fi;
config config status.showUntrackedFiles no
