#!/usr/bin/bash
if [[ $# -eq 0 ]] ; then
	echo 'Syntax: kb <code|pt|br>'
	exit 1
fi

case "$1" in
	'code')
		setxkbmap -layout us -variant altgr-intl
		echo 'Modo coding ativado (us altgr-intl)'
		echo '  deadkeys desativadas'
		echo '  Use a tecla `altgr` para usar letras com acentos'
		echo
		;;
	'pt')
		setxkbmap -layout us -variant alt-intl
		echo 'Modo português ativado (us alt-intl)'
		echo '  deadkeys ativadas'
		echo '  Teclas de acentos aguardam a próxima tecla'
		echo
		;;
	'br')
		setxkbmap -model abnt2 -layout br -variant abnt2
		echo 'Modo abnt2 ativado (bt-abnt2)'
		echo '  deadkeys ativadas'
		echo '  Teclas de acentos aguardam a próxima tecla'
		echo '  Teclas refletem o que está escrito no teclado brasileiro.'
		echo
		;;
	*)
		echo "Opção inválida: $1"
		exit 1
		;;
esac

